## Numpy의 기본 사용법

#### 리스트와 넘파이 배열의 차이

In [10]:
import numpy as np
a = [1,2,3]
sum(a)
b = np.array(a)
b.sum()
b.mean()

2.0

In [1]:
# 원소간의 합이 아닌 리스트를 연결함

In [28]:
import numpy as np   # 앞으로 numpy의 별명을 np로 한다

In [52]:
np_mid_scores = np.array([10,20,30])
np_final_scores = np.array([70,80,90])
final = np_mid_scores + np_final_scores
print(final)
print(type(final))
final * 10

#시험성적의 합계 : [ 70  90 110]
total = np_mid_scores + np_final_scores
print(final)
print(type(final))

#시험성적의 평균 : [35. 45. 55.]
print(total/2)

[ 80 100 120]
<class 'numpy.ndarray'>
[ 80 100 120]
<class 'numpy.ndarray'>
[40. 50. 60.]


 **리스트에서 배열 만들기**

In [26]:
import numpy as np

# 리스트에서 배열 만들기
print(np.array([1,4,5,2,5,3]))
print(np.array([5,4,1,2,3.14,6]))
print(np.array([1,2,3,4],dtype = 'float64'))
print(np.array([0.987654,2,3.88,4],dtype = 'int64'))

[1 4 5 2 5 3]
[5.   4.   1.   2.   3.14 6.  ]
[1. 2. 3. 4.]
[0 2 3 4]


**처음부터 배열 만들기**

In [34]:
#0으로 채운 배열 생성
print(np.zeros(10, dtype = float))

#1로 채운 배열 생성
print(np.ones(10, dtype = int))

# 3.14로 채운 배열 만들기 
print(np.full(10, 3.14))

# 0에서 시작해 2씩 더해 20까지 채우는 배열 생성
print(np.arange(0, 21, 2))

# 0과 1 사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열 만들기
print(np.linspace(0, 1, 5))

# 3*3 크기의 난수 배열 생성
print(np.random.rand(3,3))
print(np.random.random((3,3)))

# 평균 0, 표준 편차 1의 정규 분포를 따르는 3*3 난수 배열
print(np.random.normal(0, 1, (3,3)))

# [0, 10) 구간의 임의로 정수로 채운 3*3 배열 만들기
print(np.random.randint(0,10,(3,3)))

# 크기 3의 단위 행렬 만들기
print(np.())

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1 1 1 1]
[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
[ 0  2  4  6  8 10 12 14 16 18 20]
[0.   0.25 0.5  0.75 1.  ]
[[0.40573898 0.80722337 0.37295084]
 [0.07109726 0.64444545 0.12325107]
 [0.32284934 0.48871062 0.85342901]]
[[0.33245348 0.25683136 0.79198783]
 [0.4260704  0.1547784  0.68097507]
 [0.13142176 0.82426438 0.9049293 ]]
[[-0.46811631  0.69804708  2.16965614]
 [ 0.28828519  0.84373635 -0.18286783]
 [ 0.25561288  0.57945005 -2.2531596 ]]
[[6 2 0]
 [6 0 7]
 [4 9 3]]


## Note
넘파이가 계산을 쉽고 빠르게 할 수 있는 데에는 이유가 있다. 넘파이는 각 배열마다 타입이 하나만 있다고 생각한다. 다시 말하면, 넘파이의 배열 안에는 동일한 타입의 데이터만 저장할 수 있다. 즉 정수면 정수, 실수면 실수만을 저장할 수 있는 것이다. 파이썬의 리스트처럼 여러 가지 타입을 섞어서 저장할 수는 없다. 만약 여러분들이 여러 가지 타입을 섞어서 넘파이의 배열에 전달하면 넘파이는 이것을 전부 문자열로 변경한다. 예를 들어서 다음 배열은 문자열 배열이 된다. 

#### 넘파이의 핵심 다차원배열(ndarray)

In [38]:
import numpy as np
# 넘파이 ndarray 객체의 생성
tangled = np.array([100, 'test', 3.0, False])
print(tangled)
# a 객체의 형태(shape)
tangled.shape
tangled.dtype


['100' 'test' '3.0' 'False']


dtype('<U32')

In [45]:
#ndim
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]]) 
print(a.ndim)
print(b.ndim)

1
2


In [47]:
#dtype
a.dtype

dtype('int32')

In [49]:
#itemsize 메모리크기
print(a.itemsize)
print(b.itemsize)

4
4


In [50]:
#size 요소의 개수
print(a.size)
print(b.size)

3
6


In [51]:
a/a.size

array([0.33333333, 0.66666667, 1.        ])

Python의 Numpy 라이브러리는 **다양한 형태의 배열**을 초기화 할 수 있습니다.

In [68]:
import numpy as np

# 0부터 3까지의 배열 만들기
array1 = np.arange(4)
print(array1)

# 0으로 초기화 (4*4)
array2 = np.zeros((4,4), dtype = float)
print(array2)

# 1로 초기화 (4*4)
array3 = np.ones((4,4), dtype = int)
print(array3)

# 0부터 9까지 랜덤하게 초기화 된 정수 배열 만들기
array4 = np.random.randint(0, 9, (3,3))
print(array4)

# 평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0,1,(3,3))
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[6 2 2]
 [0 0 6]
 [6 0 2]]
[[ 0.27937054 -0.5240171  -0.47878239]
 [-0.09335471 -0.22040167 -0.63932166]
 [ 1.44289045  1.04927968  1.16496691]]


Python의 Numpy 라이브러리는 List와 **상호 변환이 가능**합니다.

In [63]:
import numpy as np
a = [1,2,3,4]
b = [5,6,7,8]
print(a+b)

aa = np.array([1,2,3,4])
bb = np.array([5,6,7,8])
print(aa+bb)
print(aa.size)

[1, 2, 3, 4, 5, 6, 7, 8]
[ 6  8 10 12]
4


In [69]:
import numpy as np

array = np.array([1, 2, 3])
# 배열의 크기
print(np.size)
# 배열 원소의 타입
print(array.dtype)
# 인덱스 2의 원소
print(array[2]) 

<function size at 0x000002C5770D1900>
int32
3


## 배열 속성 지정

In [77]:
#ndim(차원의 개수), shape(각 차원의 크기), size(전체 배열의 크기), dtype(데이터타입)
x = np.random.randint(10, size = (3, 4, 5), dtype = 'int8')  
print(x.ndim)
print(x.shape)
print(x.size)
print(x.itemsize)
print(x.dtype)

3
(3, 4, 5)
60
1
int8


## Numpy의 연산과 함수


####  넘파이 배열 연산

In [83]:
import numpy as np
salary = np.array([220, 250, 230])
lst = [220, 250, 230] * 2 # 반복의 개념
print(lst)
print(salary + 240) # 각각 요소에 240씩 더해줌
print(salary * 2) # 각각 요소에 2씩 곱해줌
print(salary * 2.2) # 각각 요소에 2.2씩 곱해줌


[220, 250, 230, 220, 250, 230]
[460 490 470]
[440 500 460]
[484. 550. 506.]


Python의 Numpy 라이브러리는 기본적인 상수 연산이 가능합니다.

In [1]:
import numpy as np
array = np.random.randint(1,10,size = 4).reshape(2,2)
print(array)
result_array = array * 10
print(result_array)
array2 = array + 10

[[5 2]
 [7 4]]
[[50 20]
 [70 40]]


**서로 다른 형태의 Numpy 연산**이 가능합니다.

In [2]:
import numpy as np
array1 = np.arange(4).reshape(2,2)
array2 = np.arange(2)
print(array1)
print(array2)
print(array1 + array2)

[[0 1]
 [2 3]]
[0 1]
[[0 2]
 [2 4]]


In [4]:
import numpy as np
array1 = np.arange(0,8).reshape(2,4)
array2 = np.arange(0,8).reshape(2,4)
array3 = np.concatenate([array1, array2], axis = 0)
print(array1,'\n')
print(array2,'\n')
print(array3)

[[0 1 2 3]
 [4 5 6 7]] 

[[0 1 2 3]
 [4 5 6 7]] 

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]


#### Numpy는 다양한 형태로 **합치기가 가능** 있습니다.

In [8]:
import numpy as np
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.concatenate(([array1, array2]), axis = 0)
print(array3.shape)
print(array3)

#### Numpy를 위 아래로 합칠 수 있습니다.

In [9]:
import numpy as np
array1 = np.arange(4).reshape(1,4)
array2 = np.arange(8).reshape(2,4)
array3 = np.concatenate([array1,array2],axis = 0)
print(array1,'\n')
print(array2,'\n')
print(array3.reshape,'\n')
print(array3)


[[0 1 2 3]] 

[[0 1 2 3]
 [4 5 6 7]] 

<built-in method reshape of numpy.ndarray object at 0x000001F20D173630> 

[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


Numpy의 **형태를 나누기** 할 수 있습니다.

In [15]:
import numpy as np
array = np.arange(8).reshape(2,4)
left, right = np.split(array, [1], axis = 0)
print(left)
print(right)
print(right)

print(right[0,2])

[[0 1 2 3]]
[[4 5 6 7]]
[[4 5 6 7]]
6


Numpy의 **마스킹 연산**이 가능합니다.

In [151]:
import numpy as np

# Numpy 원소의 값을 조건에 따라 바꿀 때는 다음과 같이 합니다.
# 반복문을 이용할 때보다 매우 빠르게 동작합니다.
# 대체로 이미지 처리(Image Processing)에서 자주 활용됩니다.


Numpy는 **다양한 집계 함수**가 존재합니다.

In [152]:
import numpy as np

array = np.arange(16).reshape(4, 4)
#최대값, 최소값, 합계, 평균값

In [16]:
lst = [[1,11], [2,12], [3,13]]
# => [11,12,13]
lst[2]
array = np.array(lst)
array[:,1]
print(array)


[[ 1 11]
 [ 2 12]
 [ 3 13]]


In [18]:
import numpy as np
array = np.arange(10)
print(array)
array[6]
array2 = array.reshape(2,5)
print(array2)
array.reshape(2,5)
print(array2[1,2])

[0 1 2 3 4 5 6 7 8 9]
6


In [75]:
array = np.arange(10)
print(array)
print(array[::2])
print(array[:5])
print(array<5)
lst = np.array([15,17,18,19])
age = lst<18
print(age)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 1 2 3 4]
[ True  True  True  True  True False False False False False]
[ True  True False False]


### 배열 인덱싱


In [154]:
x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3, 4))
x3 = np.random.randint(10, size = (3, 4, 5))

# x1 양수 인덱스 (맨 앞 요소)

# x1 세 번째 요소 

# x1 음수 인덱스 (맨 뒤 요소)

# x1 뒤에서 네 번째 요소 

# x2 2행 0열 (리스트 인덱스와 비교)

# list[i][j] / ndarray[i, j]
# x3 1차원, 2행, 3열 요소

# x2의 0행 0열 값을 15로 바꿈

### 배열 슬라이싱


In [155]:
x = np.arange(10) # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# array([0, 1, 2, 3, 4])

# array([5, 6, 7, 8, 9])

# array([4, 5, 6])

# array([0, 2, 4, 6, 8])

# array([1, 3, 5, 7, 9])

# array([1, 4, 7])

# array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]) 

# 배열 슬라이싱 - 다차원 하위 배열
x = np.random.randint(10, size = (4, 5))
# 두 개의 행과 세 개의 열

# 모든 행, 한 열 걸러 하나 씩

# 행을 역으로, 열도 역으로 (전치 행렬)

## Numpy의 활용

#### Python의 Numpy는 **저장 및 불러오기**가 가능합니다.

In [156]:
import numpy as np
# 단일 객체 저장 




In [157]:
#불러오기


#### 여러 개의 Numpy의 객체를 하나의 파일에 저장하고 불러올 수 있습니다.

In [158]:
import numpy as np
# 복수 객체 저장 및 불러오기
#0~9까지 정수생성

# 10 ~19 정수생성

#복수 객체 저장


#불러오기






#### Numpy의 원소들은 특정한 기준에 따라서 **정렬**할 수 있습니다.

In [159]:
import numpy as np

# Numpy 원소 오름차순 정렬


# Numpy 원소 내림차순 정렬


# 각 열을 기준으로 정렬


#### Numpy 관련 자주 사용되는 함수는 다음과 같습니다.

In [160]:
import numpy as np

# 균일한 간격으로 데이터 생성


# 난수의 재연(실행마다 결과 동일)


# Numpy 배열 객체 복사


# 중복된 원소 제거


#### Numpy는 다양한 형태로 **합치기가 가능**합니다.

In [161]:
import numpy as np



#### Numpy를 위 아래로 합칠 수 있습니다.

In [162]:
import numpy as np



#### Numpy의 **형태를 변경**할 수 있습니다.

In [163]:
import numpy as np



#### Numpy의 **형태를 나누기** 할 수 있습니다.

In [164]:
import numpy as np



###  BMI 계산하기

In [165]:
import numpy as np

heights = [ 1.83, 1.76, 1.69, 1.86, 1.77, 1.73 ]
weights = [ 86,    74,    59,   95,    80,   68  ]


### 인덱싱과 슬라이싱

In [166]:
import numpy as np
scores = np.array([88, 72, 93, 94, 89, 78, 99]) 

In [167]:
#93

In [168]:
#99

In [169]:
# 첫번째, 두번째, 세번째, 네번째 항목을 슬라이싱 함 array([72, 93, 94])

In [170]:
# 마지막 인덱스를 생략하면 디폴트 값은 -1임 array([94, 89, 78, 99])

In [171]:
# 마지막 인덱스 -1을 사용 array([89, 78])

### 논리적인 인덱싱

In [22]:
ages = np.array([18, 19, 25, 30, 28])

In [24]:
import numpy as np
# ages > 20
y = ages > 20
print(y)
y_data = ages[y]
y_data


[False False  True  True  True]


array([25, 30, 28])

In [174]:
# array([25, 30, 28])

In [26]:
x = np.arange(0,30,2)
print(x)
print(x[3])
print(x != x[3])
print(x[x != x[3]])
      

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
6
[ True  True  True False  True  True  True  True  True  True  True  True
  True  True  True]
[ 0  2  4  8 10 12 14 16 18 20 22 24 26 28]


In [ ]:
import math
a = np.sqrt([2,3,4])


In [33]:
z = np.array(range(0,30,2))
print(z)
#list comprehension
# y = np.array()
t = (1,2,3)
lst = list(t)

[i for i in range(0,30) if i % 2 == 0]
k = np.array([i for i in range(0,30) if i % 2 == 0])
print(k)

lst = list(t)
print(lst)



[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[1, 2, 3]


In [40]:
a = np.arange(6)
print(a)
b = np.array([i for i in range(6)])
print(b)
type(b)
type(a)
a2 = a[np.newaxis, :]
a2

[0 1 2 3 4 5]
[0 1 2 3 4 5]


array([[0, 1, 2, 3, 4, 5]])

In [43]:
array = np.array([1,2,3,4,5,6,7,8])
array1 = np.array([1,2,5,6,7,8])
array2 = np.array([1,2,3,'가',5,6,7,8])
print(array[1].mean())
print(array[2].shape)
print(array.mean())
print(array2)
array2[3] = 100
print(array2)
array3 = np.array(array2, dtype = float)
array3 = np.array(array2, dtype = int)
print(array3.mean())
print(array3)


2.0
()
4.5
['1' '2' '3' '가' '5' '6' '7' '8']
['1' '2' '3' '100' '5' '6' '7' '8']
16.5
[  1   2   3 100   5   6   7   8]


In [46]:
array = np.array([0,1,2,100,4,5,6,7])
idx = [2,3,5]
array2 = array[idx]
array2
print(array2)

[  2 100   5]


In [51]:
y = np.array([[51,55],[14,19],[0,4]])
print(y[0])
print(y[0][1])
print(y)
print('==================')
for row in y:
    print(row)

[51 55]
55
[[51 55]
 [14 19]
 [ 0  4]]
[51 55]
[14 19]
[0 4]


In [57]:
z = y.flatten()
print(z)
w = y.reshape(6,)
print(w)
print(w[[0,2,4]])
print(z[[0,2,4]])
print(w[w > 21])



[51 55 14 19  0  4]
[51 55 14 19  0  4]
[51 14  0]
[51 14  0]
[51 55]


###  2차원 배열

In [62]:
import numpy as np 
y = [[1,2,3], [4,5,6], [7,8,9]] 


In [63]:
#y[0][2]
z = np.array(y)[0][1]
z

z = np.array(y)[0:2][1].mean()
z

5.0

In [64]:
# np_array[0][2]

###  넘파이 스타일의 배열의 인덱싱

In [177]:
np_array = np.array([[1,2,3], [4,5,6], [7,8,9]]) 
# 3

In [178]:
#1

In [179]:
#9

In [180]:
# ndarray의 첫 요소를 변경함 1 -> 12

In [181]:
np_array[2, 2] = 1.234  # 마지막 요소의 값을 실수로 변경하려고 하면 실패
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1]])

###  넘파이 스타일의 2차원 배열 슬라이싱

In [182]:
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 


In [183]:
# array([1, 2, 3])

In [184]:
# array([5, 6])

In [185]:
np_array = np.array([[ 1,  2,  3,  4], 
                     [ 5,  6,  7,  8], 
                     [ 9, 10, 11, 12], 
                     [13, 14, 15, 16]]) 
# 첫 슬라이싱: 0행, 2행 선택, 두 번째 슬라이싱: 그 중 0행 선택

# 행 슬라이싱: 0행, 2행 선택, 열 슬라이싱: 0열 2열 선택


###  2차원 배열에서 논리적인 인덱싱

In [186]:
np_array = np.array([[1,2,3], [4,5,6], [7,8,9]]) 
# np_array > 5 일때 결과값

In [187]:
# np_array > 5 인 값출력

In [188]:
# [:, 2]

In [189]:
# [:, 2] > 5

### 2차원 배열 연습

In [190]:
import numpy as np
x = np.array( [['a', 'b', 'c', 'd'],
               ['c', 'c', 'g', 'h']])


#print(x - y)

In [191]:
mat_a = np.array( [[10, 20, 30], [10, 20, 30]])
mat_b = np.array( [[2, 2, 2], [1, 2, 3]])

# mat_a - mat_b

###  넘파이 배열의 형태 알아내고 슬라이싱하여 연산하기

In [194]:
import numpy as np 
 
x = np.array([[ 1.83, 1.76, 1.69, 1.86, 1.77, 1.73 ], 
              [ 86.0, 74.0, 59.0, 95.0, 80.0, 68.0 ]]) 
y = x[0:2, 1:3] 
z = x[0:2][1:3]



### 2차원 배열에서 특정 조건을 만족하는 행만 추출하기

In [193]:
import numpy as np 

players = [[170, 76.4], 
           [183, 86.2], 
           [181, 78.5], 
           [176, 80.1]] 


###  arange()  함수와 range() 함수의 비교

In [78]:
import numpy as np 


array([0, 1, 2, 3, 4])

array([1, 2, 3, 4, 5])

array([1, 3, 5, 7, 9])

range(0, 5)

range(0, 5, 2)

[0, 1, 2, 3, 4]

array([0, 1, 2, 3, 4])

### linspace() 함수와 logspace() 함수

### 10.14 reshape() 함수

In [4]:
import numpy as np

# array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [195]:
# reshape(3, 4)

In [127]:
# reshape(6, -1)

In [128]:
# reshape(6, 2)

In [129]:
# y.flatten()

###  난수 생성하기

In [197]:
np.random.seed(100)

###  정규 분포 난수 생성

array([-1.02933685, -0.51099219, -2.36027053,  0.10359513,  1.73881773])

### 평균과 중간값 계산하기

### 평균과 중간값 계산하기

In [201]:
import numpy as np 
 
players = np.zeros( (100, 3) ) 



### 상관관계 계산하기

In [202]:
import numpy as np 

x = [ i for i in range(100) ]
y = [ i ** 2 for i in range(100) ]


### 다수 변수들 사이의 상관관계 계산하기

### 교재실습

In [205]:
import numpy as np


In [206]:
#mean값과 동일
#3번째인덱스 가중치가 0이므로 15가 나옴
#1번째 인덱스 가중치가 0이므로 25가 나옴

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [208]:
# 인텍스3번 출력

# 6을 제외한 나머지 요소출력


In [209]:
import numpy as np


In [210]:
import math


In [211]:
#행과열 변환(tranpose())


In [212]:
z =np.array(range(0,30,2))        
print(z)
# 리스트컴프리헨션으로 작성


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [70]:
a = np.arange(6)
#list 컴프리헨션을 통해 리스트를 만든후 array로 변경



<class 'numpy.ndarray'>
[0 1 2 3 4 5]
[[0 1 2 3 4 5]]


((6,), (1, 6))

### 불리언 마스킹

In [65]:
names = np.array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan','Lee', 'Beomwoo','Park', 'Beomwoo'])
print(names)
print(names.shape)

['Beomwoo' 'Beomwoo' 'Kim' 'Joan' 'Lee' 'Beomwoo' 'Park' 'Beomwoo']
(8,)


In [68]:
data = np.random.randn(8,4)
print(data)
print(data.shape)


[[-1.62218648e-01  1.93311788e+00 -2.23367988e-01  8.10431257e-01]
 [-8.63109390e-02 -1.29187914e+00  1.71890402e-03 -1.54888164e+00]
 [ 7.62958047e-01  9.43719208e-01 -1.28881976e+00 -3.41273265e-02]
 [-7.40918981e-01 -1.19088241e+00  2.89654876e-01 -5.10237631e-01]
 [ 1.77285735e+00 -2.94358983e-01 -1.72578979e-01 -5.93047063e-01]
 [-1.02608513e-02 -5.27256458e-01 -4.02465925e-01  1.03207586e-01]
 [-2.72796885e-01 -6.70800267e-01  4.84552703e-01  4.39263576e-01]
 [-2.97556109e-01 -8.49328523e-01  4.90939167e-01  4.65813234e-01]]
(8, 4)


In [71]:
names_mask = (names == 'Beomwoo')
names_mask
print(names_mask)
names_mask = names[names == 'Beomwoo']
names_mask

[ True  True False False False  True False  True]


array(['Beomwoo', 'Beomwoo', 'Beomwoo', 'Beomwoo'], dtype='<U7')

In [213]:
import numpy as np


In [214]:
import numpy as np
#브로드캐스트는 배열의 size에 맞추어 계산이 가능토록 해주는 기능이다
# 행렬과 스칼라 연산


In [215]:
# 원소 접근


In [216]:
# Numpy만의 특이한 원소 접근법(인덱스를 배열로 지정해 여러 개 접근) ---> array 마스크
# 1차원 배열로 평탄화 [51 55 14 19 0 4]

# 인덱스가 0,2,4인 원소에 접근

# [True True False True False False]


#### linspace

In [218]:
import numpy as np


#### logspace

#### random 모튤

In [219]:
import numpy as np
#randn -> 𝝁=0 ,𝜎=1인 표준정규분포 생성(음수가 나올수있음)


In [220]:
import matplotlib.pyplot as plt
import numpy as np



In [221]:
import numpy as np


In [222]:
import numpy as np
import matplotlib.pyplot as plt


In [223]:
# rng->random generator , (0)은 seed값


In [224]:



# plt.hist(rn2)
# rn3= np.random.standard_normal(2000)
# plt.hist(rn3)

In [225]:
import matplotlib.pyplot as plt
