# About NumPy

NumPy :

데이터 사이언스등 대규모의 배열데이터를 처리하기 위해서 다차원 배열 처리에 최적화되어있는 라이브러리
파이썬 배열에 비해 더 빠른 처리를 수행가능


In [ ]:
import numpy as np

위 구문은 numpy 라이브러리를 np라는 이름으로 로딩한다.

<br><br><br>

<hr color = gray size = '10' />


# NumPy 의 기초


### Numpy 저장 및 불러오기


In [2]:
import numpy as np
#단일객체 저장
array = np.arange(0,10)
np.save('saved.npy', array)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
result = np.load('saved.npy')
print(result)
type(result)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [13]:
#복수개체 저장 및 불러오기

array1 = np.arange(0,10)
array2 = np.arange(10,20)
np.savez('saved.npz', 
         ar1 = array1, ar2 = array2)
data = np.load('saved.npz')
print(data)
result1 = data['ar1']
print(result1)

result2 = data['ar2']
print(result2)
print(result1 + result2)

a = range(10)
a

NpzFile 'saved.npz' with keys: ar1, ar2
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18 20 22 24 26 28]


range(0, 10)

In [19]:
a = np.array([5,9,10,3,1])
a.sort()
print(a)

[ 1  3  5  9 10]


In [20]:
#각 열을 기준으로 정렬
array = np.array([[5,9,10,3,1],[8,3,4,2,5]])
print(array)
array.sort(axis=0)
print(array)

[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [22]:
#난수 재연
np.random.seed(6)
print(np.random.randint(0,10,(2,3)))

[[9 3 4]
 [0 9 1]]


In [25]:
import numpy as np
height = [1.83, 1.76, 1.69, 1.86, 1.73, 1.88]
weight = [89, 73, 59, 95, 80, 68]
np_height = np.array(height)
np_weight = np.array(weight)
bmi = np_weight/(np_height**2)
print(bmi)


[26.57589059 23.56663223 20.65754    27.45982194 26.7299275  19.23947488]




## NumPy 배열 생성


In [ ]:
narr = np.array([1,2,3,4])
print(narr)

파이썬 리스트를 넘피 배열로 변환하기


In [ ]:
arr = [1,3,5]

print(narr)

실수 배열 만들기

In [ ]:

print(narr)

배열의 값을 억세스 하는 방법은 기본적으로 LiST와 유사하다.


In [ ]:
narr = np.array([1,2,3])
#첫번째, 두번째 요소 출력

narr = np.array([[1,2,3], [4,5,6]])
#출력값 1 , 4 



단 Numpy 는 다차원 배열의 값을 억세스 할때 다음의 구문도 가능하다.


In [ ]:
narr = np.array([[1,2,3], [4,5,6]])
#출력값 1 ,2, 4 


<hr>

## NumPy 배열과 파이썬 리스트의 차이

파이썬의 리스트는 자료의 저장에 촛점을 두고 있다면 Numpy 의 배열은 특히 수학적인 행렬의 표현을 더 중시한다. 이는 두 자료형의 기본연산의 차이에서 잘 드러난다.


In [ ]:
# 파이썬 배열
arr1,arr2 = [1,2,3], [4,5,6]
print( "파이썬 배열 덧셈 :",        )

# numpy 배열
narr1 = np.array(arr1)
narr2 = np.array(arr2)
 
print( "numpy 배열 덧셈 :",       )
print( "numpy 배열 곱셈 :",       )


위에서 보듯이 리스트는 + 연산자가 두 리스트의 합병을 의미하지만 Numpy 는 두 자료형의 값을 합산한 배열을 의미한다.  

또한 Numpy 는 행렬이므로 각 차원의 크기가 일정해야 한다.  예를 들어서 다음의 2차원 리스트는 Numpy 로 변환시


In [ ]:
arr1 = [[1,2], [3,4,5]]
arr2 = [[0,1,2], [3,4,5]]

narr1 = np.array(arr1)
narr2 = np.array(arr2)

print(narr1)
print(narr2)


위에서 arr1 은 두개의 List길이가 다르기 때문에 2차원 행렬로 변환이 불가능하다. 그래서 narr1은 리스트를 값으로 갖는 1차원 행렬로 변황이 되었지만 narr2 는 2x3 으로 변환이 가능하므로 2차원 행렬로 변환되었다.  


<hr>

## Shape , Reshape

NumPy 배열은 다차원 배열을 기본적으로 지원하며 모든 NumPy 배열은 shape 메소드를 통해 그 차원을 알아볼 수 있다.

```
narr = np.array([[1,2,3],[4,5,6]])
print(narr.shape)
-> (2,3)
```
다음의 예제는 여러 numpy 배열과 그 shape 를 출력한다.

In [2]:
import numpy as np
narr1 = np.array([1,2,3])
narr2 = np.array([[1,2,3]])
narr3 = np.array([[1],[2],[3]])
narr4 = np.array([[[1,2],[3,4]]])

for narr in [narr1, narr2, narr3, narr4]:
  print(narr)
  print(len(narr.shape), "차원 배열 -> ",narr.shape )
  print()


[1 2 3]
1 차원 배열 ->  (3,)

[[1 2 3]]
2 차원 배열 ->  (1, 3)

[[1]
 [2]
 [3]]
2 차원 배열 ->  (3, 1)

[[[1 2]
  [3 4]]]
3 차원 배열 ->  (1, 2, 2)



Reshape를 이용하면 배열의 차원이나 형태의 변경이 가능하다.  예를 들어 (2,4) 인 형태의 배열을 (1,8) 이나 (2,2,2) 등으로 변경할 수 있다.



In [2]:
import numpy as np
narr = np.array([1,2,3,4,5,6,7,8])
# 1x8
# 2x4
# 4x2
# 2x2x2



<hr>

## 배열 초기화

위에서 나온 np.array([1,2,3]) 처럼 배열을 직접 값을 줘서 만들 수 도 있지만 크기가 큰 배열의 경우 주로 초기화 루틴을 통해 만들 수 있다. 이때 배열의 크기와 형태는 shape 값을 인자로 입력한다.  

<b> 0 으로 초기화 </b>

In [7]:
import numpy as np
# 3 x 2 를 0으로 초기화

print(narr)

<b> 특정 값으로 초기화 </b>

In [8]:
import numpy as np
# 2 x 4 를 7로 초기화

print(narr)



## 배열의 범위지정

파이썬의 리스트는 ':' 를 이용한 범위지정이 가능하다.
```
l = [1,2,3,4,5]
print(l[1:4])
-> 2,3,4
```
Numpy 도 이러한 범위지정을 사용할 수 있다.


In [10]:
import numpy as np
narr = np.array([1,2,3,4])
# 전체출력 [:]
# [1] 출력
# [2 3 4] 출력
# [1 2 3] 출력
# [2 3] 출력


이러한 범위지정은 다차원 배열에서 그 활용도가 더욱 커진다.


In [12]:
import numpy as np
narr2 = np.array([[1,2,3], [4,5,6]])
# 1출력

#  [[1 2 3]
# [4 5 6]]  출력
# 첫째 줄 출력
# 둘째 열 출력


이러한 범위지정을 이용해 배열의 일부에 대해 원하는 값을 대입할 수도 있다.

### <font color = 'red'> 연습문제 1-1 : 반복문 없이 다음과 같은 Numpy 배열을 만들기  </font>

```
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
 ```



In [20]:
narr = np.zeros((10,10))
#연습문제 1-1 을 여기에 작성해보세요

print(narr)

### <font color = 'red'> 연습문제 1-2 : 반복문 없이 다음과 같은 Numpy 배열을 만들기  </font>

```
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 2. 2. 2. 2. 2. 2. 1. 0.]
 [0. 1. 2. 2. 2. 2. 2. 2. 1. 0.]
 [0. 1. 2. 2. 2. 2. 2. 2. 1. 0.]
 [0. 1. 2. 2. 2. 2. 2. 2. 1. 0.]
 [0. 1. 2. 2. 2. 2. 2. 2. 1. 0.]
 [0. 1. 2. 2. 2. 2. 2. 2. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
 ```



In [ ]:
narr = np.zeros((10,10))
#연습문제 1-2 을 여기에 작성해보세요


print(narr)

### <font color = 'red'> 연습문제 1-3 :  반복문 없이 임의의 짝수크기 배열의 홀수 위치만 0으로 변환

예: [1,2,3,4,5,6] -> [1,0,3,0,5,0]

참고 : 배열 길이의 반 = int( len(arr) / 2)






In [23]:
narr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
l = int( len(narr) / 2 )
#연습문제 1-3 풀이를 작성해보세요



[ 0  2  0  4  0  6  0  8  0 10  0 12]
